### ISSUE TITLE
metric convention

### ISSUE THREAD

**Issue by JohannesKonings** [Goala/abap-metrics-provider#10]
-  metrics store and dependet object
=> category (system), key (shortdumps_no), value (3)

**Comment by JohannesKonings** [comment]
maybe:
<<sysid>>_<<client>>_<<metric group name>>_<<metric name>>

**Comment by Goala** [comment]
@JohannesKonings  if you meant something like that
`<<sysid>>_<<client>>_<<metric group name>>_<<metric name>>`
i'm good with it
