### ISSUE TITLE
DDIC table or shared objects for metrics store?

### ISSUE THREAD

**Issue by JohannesKonings** [Goala/abap-metrics-provider#15]
e.g. https://github.com/pacroy/abap-prometheus is based on shared objects.
Currently it's implemented as a DDIC table: https://github.com/Goala/abap-metrics-provider/blob/master/src/zamp_store.tabl.xml

**Comment by Goala** [comment]
@JohannesKonings I think we can close this. We already highly integrated the zamp_store table. What do you think?

**Comment by JohannesKonings** [comment]
@Goala maybe with a lot of metrics and a lot of requests shared objects are maybe better for the system performance.
We can close this, but should have an eye on the performance and the alternatives.
