### ISSUE TITLE
scenario for Provider and Scrapper?

### ISSUE THREAD

**Issue by JohannesKonings** [Goala/abap-metrics-provider#26]
Should the scenario only be used in the component provider or also in the scrapper.
A scenario could be a bracket around the metrics for specific collection frequency, but it can also be used from different metric targets.

This only affects the query on the metric store.

**Comment by JohannesKonings** [comment]
Because the converter depends on the scenario, it is easier to use the scenario also for the scrapper

**Comment by Goala** [comment]
I would use the scenario as bracket to reduce selection size. 
We could also define specific database tables for different scenarios to separate data from each other and prevent overwriting metrics between different scenarios
