### ISSUE TITLE
Current naming of metric keys repeat the name of the metric group

### ISSUE THREAD

**Issue by ThoralfHaensel** [Goala/abap-metrics-provider#73]
Example with prometheus key value converter:
SID_100_prometheus_jobs_jobs_aborted
SID_100_prometheus_jobs_jobs_finished
SID_100_prometheus_runtime_errors_runtime_errors
SID_100_prometheus_workloads_workload_no_of_records
 
Proposal:
SID_100_prometheus_jobs_aborted
SID_100_prometheus_jobs_finished 
SID_100_prometheus_runtime_errors_number
SID_100_prometheus_workloads_no_of_records

**Comment by Goala** [comment]
resolved with https://github.com/Goala/abap-metrics-provider/pull/74
